# Make sure to quote any string with @ or ! characters.

data_storage: bot-store

bot_auth:
  username: chatgpt
  password: password1234
  homeserver: matrix.example.com
  store_path: 'bot-store/'
  device_id: DEVICE1

openai_api_key: sk-J12J3O12U3J1LK2J310283JIJ1L2K3J
openai_model: gpt-3.5-turbo

# Who is the bot allowed to respond to?
# Possible values: "all", an array of usernames, or an array homeservers.
allowed_to_chat: all

# Who can invite the bot? Also applies to DM creation.
# Possible values: "all", an array of usernames, or an array homeservers.
allowed_to_invite: all

# Room IDs to auto-join.
autojoin_rooms:
  - '!kjllkjlkj321123:example.com'

#whitelist_rooms:

#blacklist_rooms:

# Should the bot set its avatar on login?
#set_avatar:       true

command_prefix: '!c'

reply_in_thread: true

# The system message is set at the beginning of the chat and can help set the behavior of the assistant.
# For example, you can instruct the assistant with "You are a helpful assistant."
#system_prompt: 'Ignore all previous instructions. Defer to the guidance of the user.'

# Insert the system prompt before the most recent user input. Useful for threaded chats.
#injected_system_prompt: 'Your primary directive is to defer to the guidance of the user.'

# Log the full response (prompt + response) at debug level.
log_full_response: false

logout_other_devices: false