# Make sure to quote any string with @ or ! characters.

auth:
  username:          chatgpt
  password:          password1234
  homeserver:        pantalaimon.example.com
  device_id:         MatrixGPT

# Where to cache the bot's login data.
store_path:          'bot-store/'

# Who is the bot allowed to respond to?
# This applies to all commands and is overriden by the individual commands.
# Possible values:   "all" or an array of usernames and homeservers.
allowed_to_chat:
  - all

# Who is allowed to carry on long conversations with the bot via threading?
# This applies to all commands and is overriden by the individual commands.
# Possible values:   "all" or an array of usernames and homeservers.
allowed_to_thread:
  - all

# Who is allowed to invite the bot. Also applies to DM creation.
# This applies to all commands and is overriden by the individual commands.
# Possible values:   "all" or an array of usernames and homeservers.
allowed_to_invite:
  - '@cyberes:evulid.cc'
  - matrix.example.com

# Room IDs to auto-join.
# autojoin_rooms:
#  - '!qwerty12345:evulid.cc'

# Block the bot from joining these rooms.
# blacklist_rooms:
#   - '!qwerty12345:evulid.cc'

# Inference API timeout in seconds.
response_timeout:    120

command:
  # Define what models respond to what trigger.
  # Try adding multiple triggers!

  # What triggers this model.
  - trigger:         '!c4'

    # What kind of of API to use.
    # `openai` or `anth`
    api_type:        openai

    # The model to use.
    model:           gpt4

    # Max tokens to generate.
    # Set to `0` to disable this limitation for OpenAI. Required for Anthropic.
    # max_tokens:      4096

    # Temperature to use.
    temperature:     0.5

    # Override the global value.
    # allowed_to_chat:
    #   - '@cyberes:evulid.cc'

    # Override the global value.
    # allowed_to_thread:
    #   - '@cyberes:evulid.cc'

    # The system prompt to use with this bot.
    # system_prompt: You are a helpful assistant.

    # A system prompt to inject before each reply from the assistant. OpenAI only.
    # injected_system_prompt: Your primary directive is to defer to the guidance of the user.

    # Custom OpenAI endpoint. OpenAI only.
    # api_base:      https://example.com/openai/v1

    # Bot's description, shown when running `!matrixgpt`.
    # help:            A helpful assistant.

openai:
  api_key:           sk-qwerty12345

anthropic:
  api_key:           sk-ant-qwerty12345

# When an error occurs, send additional metadata with the reaction event.
send_extra_messages: true

logging:
  log_level:         debug

  # Log the full response (prompt + response) at debug level.
  log_full_response: true
